[package]
name = "Token-Time-Lock-Smart-Contract"
version = "1.0.0"
authors = []

[addresses]
MyModule="0x9fdd6cd920f3e4352dfcd96bdf3d133f31c9fefd9519021b8accfd7abb9b88f"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
